// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with no fields
func (_m *MockService) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockService_Expecter) Start() *MockService_Start_Call {
	return &MockService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockService_Start_Call) Run(run func()) *MockService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Start_Call) Return(_a0 error) *MockService_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Start_Call) RunAndReturn(run func() error) *MockService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
