port: "25000"

# Logging Configuration
logDir: "/opt/custom-logs"
logFile: "autoinstall_report.log"

# Database Configuration
database:
  host: "cockroachdb"
  port: 26257
  user: "admin"
  password: "securepassword"
  dbname: "autoinstall"
  sslmode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

boot_customization_folder: "/var/www/html/ipxe/boot"
# iPXE Settings
ipxe_folder: "/var/www/html/ipxe"

# Cloud-Init Settings
cloud_init_folder: "/var/www/html/cloud-init/"
