port: "25000"
logDir: "/opt/custom-logs"
logFile: "autoinstall_report.log"
database:
  host: "cockroachdb"
  port: 26257
  user: "admin"
  password: "securepassword"
  dbname: "autoinstall"
  sslmode: "disable"


# iPXE Settings
ipxe_folder: "/var/www/html/ipxe"
boot_customization_folder: "/var/www/html/ipxe/boot"

# Cloud-Init Settings
cloud_init_folder: "/var/www/html/cloud-init/"
