// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/certadmin.proto

package certadmin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertAdmin_Login_FullMethodName                 = "/certadmin.CertAdmin/Login"
	CertAdmin_GetCA_FullMethodName                 = "/certadmin.CertAdmin/GetCA"
	CertAdmin_IssueCertificate_FullMethodName      = "/certadmin.CertAdmin/IssueCertificate"
	CertAdmin_RenewCertificate_FullMethodName      = "/certadmin.CertAdmin/RenewCertificate"
	CertAdmin_RevokeCertificate_FullMethodName     = "/certadmin.CertAdmin/RevokeCertificate"
	CertAdmin_ListCertificates_FullMethodName      = "/certadmin.CertAdmin/ListCertificates"
	CertAdmin_GetCertificateDetails_FullMethodName = "/certadmin.CertAdmin/GetCertificateDetails"
	CertAdmin_GetServerMetrics_FullMethodName      = "/certadmin.CertAdmin/GetServerMetrics"
)

// CertAdminClient is the client API for CertAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CertAdmin service for certificate administration
type CertAdminClient interface {
	// Authentication
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// GetCA retrieves the CA certificate
	GetCA(ctx context.Context, in *GetCARequest, opts ...grpc.CallOption) (*GetCAResponse, error)
	// IssueCertificate issues a certificate from a CSR
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error)
	// RenewCertificate renews an existing certificate
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
	// RevokeCertificate revokes a certificate
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// ListCertificates lists all issued certificates
	ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	// Admin operations
	GetCertificateDetails(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CertificateDetails, error)
	GetServerMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerMetrics, error)
}

type certAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewCertAdminClient(cc grpc.ClientConnInterface) CertAdminClient {
	return &certAdminClient{cc}
}

func (c *certAdminClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, CertAdmin_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) GetCA(ctx context.Context, in *GetCARequest, opts ...grpc.CallOption) (*GetCAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCAResponse)
	err := c.cc.Invoke(ctx, CertAdmin_GetCA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCertificateResponse)
	err := c.cc.Invoke(ctx, CertAdmin_IssueCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, CertAdmin_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, CertAdmin_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, CertAdmin_ListCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) GetCertificateDetails(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*CertificateDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateDetails)
	err := c.cc.Invoke(ctx, CertAdmin_GetCertificateDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certAdminClient) GetServerMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerMetrics)
	err := c.cc.Invoke(ctx, CertAdmin_GetServerMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertAdminServer is the server API for CertAdmin service.
// All implementations must embed UnimplementedCertAdminServer
// for forward compatibility.
//
// CertAdmin service for certificate administration
type CertAdminServer interface {
	// Authentication
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// GetCA retrieves the CA certificate
	GetCA(context.Context, *GetCARequest) (*GetCAResponse, error)
	// IssueCertificate issues a certificate from a CSR
	IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error)
	// RenewCertificate renews an existing certificate
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	// RevokeCertificate revokes a certificate
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// ListCertificates lists all issued certificates
	ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	// Admin operations
	GetCertificateDetails(context.Context, *GetRequest) (*CertificateDetails, error)
	GetServerMetrics(context.Context, *Empty) (*ServerMetrics, error)
	mustEmbedUnimplementedCertAdminServer()
}

// UnimplementedCertAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertAdminServer struct{}

func (UnimplementedCertAdminServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedCertAdminServer) GetCA(context.Context, *GetCARequest) (*GetCAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCA not implemented")
}
func (UnimplementedCertAdminServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedCertAdminServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedCertAdminServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedCertAdminServer) ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificates not implemented")
}
func (UnimplementedCertAdminServer) GetCertificateDetails(context.Context, *GetRequest) (*CertificateDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificateDetails not implemented")
}
func (UnimplementedCertAdminServer) GetServerMetrics(context.Context, *Empty) (*ServerMetrics, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerMetrics not implemented")
}
func (UnimplementedCertAdminServer) mustEmbedUnimplementedCertAdminServer() {}
func (UnimplementedCertAdminServer) testEmbeddedByValue()                   {}

// UnsafeCertAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertAdminServer will
// result in compilation errors.
type UnsafeCertAdminServer interface {
	mustEmbedUnimplementedCertAdminServer()
}

func RegisterCertAdminServer(s grpc.ServiceRegistrar, srv CertAdminServer) {
	// If the following call pancis, it indicates UnimplementedCertAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertAdmin_ServiceDesc, srv)
}

func _CertAdmin_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_GetCA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).GetCA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_GetCA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).GetCA(ctx, req.(*GetCARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_ListCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).ListCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_ListCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).ListCertificates(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_GetCertificateDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).GetCertificateDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_GetCertificateDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).GetCertificateDetails(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertAdmin_GetServerMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertAdminServer).GetServerMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertAdmin_GetServerMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertAdminServer).GetServerMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CertAdmin_ServiceDesc is the grpc.ServiceDesc for CertAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "certadmin.CertAdmin",
	HandlerType: (*CertAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _CertAdmin_Login_Handler,
		},
		{
			MethodName: "GetCA",
			Handler:    _CertAdmin_GetCA_Handler,
		},
		{
			MethodName: "IssueCertificate",
			Handler:    _CertAdmin_IssueCertificate_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _CertAdmin_RenewCertificate_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _CertAdmin_RevokeCertificate_Handler,
		},
		{
			MethodName: "ListCertificates",
			Handler:    _CertAdmin_ListCertificates_Handler,
		},
		{
			MethodName: "GetCertificateDetails",
			Handler:    _CertAdmin_GetCertificateDetails_Handler,
		},
		{
			MethodName: "GetServerMetrics",
			Handler:    _CertAdmin_GetServerMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/certadmin.proto",
}
