// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CertIssuer is an autogenerated mock type for the CertIssuer type
type CertIssuer struct {
	mock.Mock
}

type CertIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *CertIssuer) EXPECT() *CertIssuer_Expecter {
	return &CertIssuer_Expecter{mock: &_m.Mock}
}

// GetRootCA provides a mock function with no fields
func (_m *CertIssuer) GetRootCA() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRootCA")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertIssuer_GetRootCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootCA'
type CertIssuer_GetRootCA_Call struct {
	*mock.Call
}

// GetRootCA is a helper method to define mock.On call
func (_e *CertIssuer_Expecter) GetRootCA() *CertIssuer_GetRootCA_Call {
	return &CertIssuer_GetRootCA_Call{Call: _e.mock.On("GetRootCA")}
}

func (_c *CertIssuer_GetRootCA_Call) Run(run func()) *CertIssuer_GetRootCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CertIssuer_GetRootCA_Call) Return(_a0 []byte, _a1 error) *CertIssuer_GetRootCA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertIssuer_GetRootCA_Call) RunAndReturn(run func() ([]byte, error)) *CertIssuer_GetRootCA_Call {
	_c.Call.Return(run)
	return _c
}

// IssueCertificate provides a mock function with given fields: csr, clientInfo
func (_m *CertIssuer) IssueCertificate(csr []byte, clientInfo map[string]string) ([]byte, error) {
	ret := _m.Called(csr, clientInfo)

	if len(ret) == 0 {
		panic("no return value specified for IssueCertificate")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, map[string]string) ([]byte, error)); ok {
		return rf(csr, clientInfo)
	}
	if rf, ok := ret.Get(0).(func([]byte, map[string]string) []byte); ok {
		r0 = rf(csr, clientInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, map[string]string) error); ok {
		r1 = rf(csr, clientInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertIssuer_IssueCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueCertificate'
type CertIssuer_IssueCertificate_Call struct {
	*mock.Call
}

// IssueCertificate is a helper method to define mock.On call
//   - csr []byte
//   - clientInfo map[string]string
func (_e *CertIssuer_Expecter) IssueCertificate(csr interface{}, clientInfo interface{}) *CertIssuer_IssueCertificate_Call {
	return &CertIssuer_IssueCertificate_Call{Call: _e.mock.On("IssueCertificate", csr, clientInfo)}
}

func (_c *CertIssuer_IssueCertificate_Call) Run(run func(csr []byte, clientInfo map[string]string)) *CertIssuer_IssueCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(map[string]string))
	})
	return _c
}

func (_c *CertIssuer_IssueCertificate_Call) Return(_a0 []byte, _a1 error) *CertIssuer_IssueCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertIssuer_IssueCertificate_Call) RunAndReturn(run func([]byte, map[string]string) ([]byte, error)) *CertIssuer_IssueCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// RenewCertificate provides a mock function with given fields: cert
func (_m *CertIssuer) RenewCertificate(cert []byte) ([]byte, error) {
	ret := _m.Called(cert)

	if len(ret) == 0 {
		panic("no return value specified for RenewCertificate")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(cert)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(cert)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(cert)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertIssuer_RenewCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenewCertificate'
type CertIssuer_RenewCertificate_Call struct {
	*mock.Call
}

// RenewCertificate is a helper method to define mock.On call
//   - cert []byte
func (_e *CertIssuer_Expecter) RenewCertificate(cert interface{}) *CertIssuer_RenewCertificate_Call {
	return &CertIssuer_RenewCertificate_Call{Call: _e.mock.On("RenewCertificate", cert)}
}

func (_c *CertIssuer_RenewCertificate_Call) Run(run func(cert []byte)) *CertIssuer_RenewCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *CertIssuer_RenewCertificate_Call) Return(_a0 []byte, _a1 error) *CertIssuer_RenewCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertIssuer_RenewCertificate_Call) RunAndReturn(run func([]byte) ([]byte, error)) *CertIssuer_RenewCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// NewCertIssuer creates a new instance of CertIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertIssuer {
	mock := &CertIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
