// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileEditor is an autogenerated mock type for the FileEditor type
type FileEditor struct {
	mock.Mock
}

type FileEditor_Expecter struct {
	mock *mock.Mock
}

func (_m *FileEditor) EXPECT() *FileEditor_Expecter {
	return &FileEditor_Expecter{mock: &_m.Mock}
}

// CreateCloudInitDirs provides a mock function with given fields: macAddress, hostname
func (_m *FileEditor) CreateCloudInitDirs(macAddress string, hostname string) error {
	ret := _m.Called(macAddress, hostname)

	if len(ret) == 0 {
		panic("no return value specified for CreateCloudInitDirs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(macAddress, hostname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileEditor_CreateCloudInitDirs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCloudInitDirs'
type FileEditor_CreateCloudInitDirs_Call struct {
	*mock.Call
}

// CreateCloudInitDirs is a helper method to define mock.On call
//   - macAddress string
//   - hostname string
func (_e *FileEditor_Expecter) CreateCloudInitDirs(macAddress interface{}, hostname interface{}) *FileEditor_CreateCloudInitDirs_Call {
	return &FileEditor_CreateCloudInitDirs_Call{Call: _e.mock.On("CreateCloudInitDirs", macAddress, hostname)}
}

func (_c *FileEditor_CreateCloudInitDirs_Call) Run(run func(macAddress string, hostname string)) *FileEditor_CreateCloudInitDirs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *FileEditor_CreateCloudInitDirs_Call) Return(_a0 error) *FileEditor_CreateCloudInitDirs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileEditor_CreateCloudInitDirs_Call) RunAndReturn(run func(string, string) error) *FileEditor_CreateCloudInitDirs_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCloudInitFiles provides a mock function with given fields: files
func (_m *FileEditor) ValidateCloudInitFiles(files map[string][]byte) error {
	ret := _m.Called(files)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCloudInitFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string][]byte) error); ok {
		r0 = rf(files)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileEditor_ValidateCloudInitFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCloudInitFiles'
type FileEditor_ValidateCloudInitFiles_Call struct {
	*mock.Call
}

// ValidateCloudInitFiles is a helper method to define mock.On call
//   - files map[string][]byte
func (_e *FileEditor_Expecter) ValidateCloudInitFiles(files interface{}) *FileEditor_ValidateCloudInitFiles_Call {
	return &FileEditor_ValidateCloudInitFiles_Call{Call: _e.mock.On("ValidateCloudInitFiles", files)}
}

func (_c *FileEditor_ValidateCloudInitFiles_Call) Run(run func(files map[string][]byte)) *FileEditor_ValidateCloudInitFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string][]byte))
	})
	return _c
}

func (_c *FileEditor_ValidateCloudInitFiles_Call) Return(_a0 error) *FileEditor_ValidateCloudInitFiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileEditor_ValidateCloudInitFiles_Call) RunAndReturn(run func(map[string][]byte) error) *FileEditor_ValidateCloudInitFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateIpxeFile provides a mock function with given fields: content
func (_m *FileEditor) ValidateIpxeFile(content []byte) error {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for ValidateIpxeFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileEditor_ValidateIpxeFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateIpxeFile'
type FileEditor_ValidateIpxeFile_Call struct {
	*mock.Call
}

// ValidateIpxeFile is a helper method to define mock.On call
//   - content []byte
func (_e *FileEditor_Expecter) ValidateIpxeFile(content interface{}) *FileEditor_ValidateIpxeFile_Call {
	return &FileEditor_ValidateIpxeFile_Call{Call: _e.mock.On("ValidateIpxeFile", content)}
}

func (_c *FileEditor_ValidateIpxeFile_Call) Run(run func(content []byte)) *FileEditor_ValidateIpxeFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *FileEditor_ValidateIpxeFile_Call) Return(_a0 error) *FileEditor_ValidateIpxeFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileEditor_ValidateIpxeFile_Call) RunAndReturn(run func([]byte) error) *FileEditor_ValidateIpxeFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteIpxeFile provides a mock function with given fields: macAddress, content
func (_m *FileEditor) WriteIpxeFile(macAddress string, content []byte) error {
	ret := _m.Called(macAddress, content)

	if len(ret) == 0 {
		panic("no return value specified for WriteIpxeFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(macAddress, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileEditor_WriteIpxeFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteIpxeFile'
type FileEditor_WriteIpxeFile_Call struct {
	*mock.Call
}

// WriteIpxeFile is a helper method to define mock.On call
//   - macAddress string
//   - content []byte
func (_e *FileEditor_Expecter) WriteIpxeFile(macAddress interface{}, content interface{}) *FileEditor_WriteIpxeFile_Call {
	return &FileEditor_WriteIpxeFile_Call{Call: _e.mock.On("WriteIpxeFile", macAddress, content)}
}

func (_c *FileEditor_WriteIpxeFile_Call) Run(run func(macAddress string, content []byte)) *FileEditor_WriteIpxeFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *FileEditor_WriteIpxeFile_Call) Return(_a0 error) *FileEditor_WriteIpxeFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileEditor_WriteIpxeFile_Call) RunAndReturn(run func(string, []byte) error) *FileEditor_WriteIpxeFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileEditor creates a new instance of FileEditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileEditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileEditor {
	mock := &FileEditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
