// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/jdfalk/ubuntu-autoinstall-webhook/pkg/proto"
)

// InstallServiceClient is an autogenerated mock type for the InstallServiceClient type
type InstallServiceClient struct {
	mock.Mock
}

type InstallServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InstallServiceClient) EXPECT() *InstallServiceClient_Expecter {
	return &InstallServiceClient_Expecter{mock: &_m.Mock}
}

// ReportStatus provides a mock function with given fields: ctx, in, opts
func (_m *InstallServiceClient) ReportStatus(ctx context.Context, in *proto.StatusRequest, opts ...grpc.CallOption) (*proto.StatusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 *proto.StatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.StatusRequest, ...grpc.CallOption) (*proto.StatusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.StatusRequest, ...grpc.CallOption) *proto.StatusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.StatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.StatusRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstallServiceClient_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type InstallServiceClient_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.StatusRequest
//   - opts ...grpc.CallOption
func (_e *InstallServiceClient_Expecter) ReportStatus(ctx interface{}, in interface{}, opts ...interface{}) *InstallServiceClient_ReportStatus_Call {
	return &InstallServiceClient_ReportStatus_Call{Call: _e.mock.On("ReportStatus",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *InstallServiceClient_ReportStatus_Call) Run(run func(ctx context.Context, in *proto.StatusRequest, opts ...grpc.CallOption)) *InstallServiceClient_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.StatusRequest), variadicArgs...)
	})
	return _c
}

func (_c *InstallServiceClient_ReportStatus_Call) Return(_a0 *proto.StatusResponse, _a1 error) *InstallServiceClient_ReportStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InstallServiceClient_ReportStatus_Call) RunAndReturn(run func(context.Context, *proto.StatusRequest, ...grpc.CallOption) (*proto.StatusResponse, error)) *InstallServiceClient_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewInstallServiceClient creates a new instance of InstallServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstallServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstallServiceClient {
	mock := &InstallServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
