// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeInstallServiceServer is an autogenerated mock type for the UnsafeInstallServiceServer type
type UnsafeInstallServiceServer struct {
	mock.Mock
}

type UnsafeInstallServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeInstallServiceServer) EXPECT() *UnsafeInstallServiceServer_Expecter {
	return &UnsafeInstallServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedInstallServiceServer provides a mock function with no fields
func (_m *UnsafeInstallServiceServer) mustEmbedUnimplementedInstallServiceServer() {
	_m.Called()
}

// UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedInstallServiceServer'
type UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedInstallServiceServer is a helper method to define mock.On call
func (_e *UnsafeInstallServiceServer_Expecter) mustEmbedUnimplementedInstallServiceServer() *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	return &UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedInstallServiceServer")}
}

func (_c *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call) Run(run func()) *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call) Return() *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call) RunAndReturn(run func()) *UnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewUnsafeInstallServiceServer creates a new instance of UnsafeInstallServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeInstallServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeInstallServiceServer {
	mock := &UnsafeInstallServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
