# file: .github/linters/.eslintrc.yml
# version: 1.0.0
# guid: b3c4d5e6-f7a8-9b0c-1d2e-3f4a5b6c7d8e

extends:
  - eslint:recommended
  - "@typescript-eslint/recommended"
  - google

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

env:
  browser: true
  es2021: true
  node: true
  jest: true

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - code: 80
      ignoreUrls: true
  no-console: warn
  no-unused-vars: error
  no-var: error
  prefer-const: error
  eqeqeq: error
  no-trailing-spaces: error
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
  no-multi-spaces: error
  keyword-spacing: error
  space-before-blocks: error
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  computed-property-spacing:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  arrow-spacing: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase: error
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  dot-notation: error
  func-call-spacing:
    - error
    - never
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  no-whitespace-before-property: error
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  padded-blocks:
    - error
    - never
  rest-spread-spacing:
    - error
    - never
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  spaced-comment:
    - error
    - always
  switch-colon-spacing: error
  template-curly-spacing:
    - error
    - never
