// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockUnsafeInstallServiceServer is an autogenerated mock type for the UnsafeInstallServiceServer type
type MockUnsafeInstallServiceServer struct {
	mock.Mock
}

type MockUnsafeInstallServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeInstallServiceServer) EXPECT() *MockUnsafeInstallServiceServer_Expecter {
	return &MockUnsafeInstallServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedInstallServiceServer provides a mock function with no fields
func (_m *MockUnsafeInstallServiceServer) mustEmbedUnimplementedInstallServiceServer() {
	_m.Called()
}

// MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedInstallServiceServer'
type MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedInstallServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeInstallServiceServer_Expecter) mustEmbedUnimplementedInstallServiceServer() *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	return &MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedInstallServiceServer")}
}

func (_c *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call) Run(run func()) *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call) Return() *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call) RunAndReturn(run func()) *MockUnsafeInstallServiceServer_mustEmbedUnimplementedInstallServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeInstallServiceServer creates a new instance of MockUnsafeInstallServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeInstallServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeInstallServiceServer {
	mock := &MockUnsafeInstallServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
