// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: install.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstallService_ReportStatus_FullMethodName = "/install.InstallService/ReportStatus"
)

// InstallServiceClient is the client API for InstallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for installation status updates.
type InstallServiceClient interface {
	// Report installation status from the client.
	ReportStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type installServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstallServiceClient(cc grpc.ClientConnInterface) InstallServiceClient {
	return &installServiceClient{cc}
}

func (c *installServiceClient) ReportStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, InstallService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstallServiceServer is the server API for InstallService service.
// All implementations must embed UnimplementedInstallServiceServer
// for forward compatibility.
//
// Service for installation status updates.
type InstallServiceServer interface {
	// Report installation status from the client.
	ReportStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedInstallServiceServer()
}

// UnimplementedInstallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstallServiceServer struct{}

func (UnimplementedInstallServiceServer) ReportStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedInstallServiceServer) mustEmbedUnimplementedInstallServiceServer() {}
func (UnimplementedInstallServiceServer) testEmbeddedByValue()                        {}

// UnsafeInstallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstallServiceServer will
// result in compilation errors.
type UnsafeInstallServiceServer interface {
	mustEmbedUnimplementedInstallServiceServer()
}

func RegisterInstallServiceServer(s grpc.ServiceRegistrar, srv InstallServiceServer) {
	// If the following call pancis, it indicates UnimplementedInstallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstallService_ServiceDesc, srv)
}

func _InstallService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstallService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallServiceServer).ReportStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstallService_ServiceDesc is the grpc.ServiceDesc for InstallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "install.InstallService",
	HandlerType: (*InstallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _InstallService_ReportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "install.proto",
}
